In [1]:
import torch 
import torchvision 
from torch.utils.data import Dataset,DataLoader 
import numpy as np 

In [10]:
class WineDatset(Dataset):

    def __init__(self) -> None:
        super().__init__()
        xy  = np.loadtxt("../wine.csv",delimiter=",",dtype = np.float32,skiprows=1)
        self.x = torch.from_numpy(xy[:,1:])
        self.y = torch.from_numpy(xy[:,:1])
        self.n_samples = xy.shape[0]

    
    def __len__(self):
        return self.n_samples


    
    def __getitem__(self, index):
        return self.x[index],self.y[index]









In [11]:
dataset = WineDatset()

In [12]:
first_dataset = dataset[0]

In [14]:
features,label = first_dataset
features,label

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
         3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
         1.0650e+03]),
 tensor([1.]))

In [19]:
dataloader = DataLoader(dataset = dataset,batch_size=4,shuffle=True)

dataiter = iter(dataloader)

data = next(dataiter)

data




[tensor([[1.3490e+01, 3.5900e+00, 2.1900e+00, 1.9500e+01, 8.8000e+01, 1.6200e+00,
          4.8000e-01, 5.8000e-01, 8.8000e-01, 5.7000e+00, 8.1000e-01, 1.8200e+00,
          5.8000e+02],
         [1.3110e+01, 1.9000e+00, 2.7500e+00, 2.5500e+01, 1.1600e+02, 2.2000e+00,
          1.2800e+00, 2.6000e-01, 1.5600e+00, 7.1000e+00, 6.1000e-01, 1.3300e+00,
          4.2500e+02],
         [1.2370e+01, 1.6300e+00, 2.3000e+00, 2.4500e+01, 8.8000e+01, 2.2200e+00,
          2.4500e+00, 4.0000e-01, 1.9000e+00, 2.1200e+00, 8.9000e-01, 2.7800e+00,
          3.4200e+02],
         [1.4210e+01, 4.0400e+00, 2.4400e+00, 1.8900e+01, 1.1100e+02, 2.8500e+00,
          2.6500e+00, 3.0000e-01, 1.2500e+00, 5.2400e+00, 8.7000e-01, 3.3300e+00,
          1.0800e+03]]),
 tensor([[3.],
         [3.],
         [2.],
         [1.]])]

In [20]:
## dummy training loop
import math
num_epochs = 2 
total_samples = len(dataset)

n_iteration = math.ceil(total_samples/4)

In [21]:
for epoch in range(num_epochs):

    for i, (inputs,labels) in enumerate(dataloader):
        # forward backword , update
        if i%5==0:
            print(f"Epoch: {epoch+1}/{num_epochs},steps {i+1}/{n_iteration}, inputs: {inputs.shape} ")

Epoch: 1/2,steps 1/45, inputs: torch.Size([4, 13]) 
Epoch: 1/2,steps 6/45, inputs: torch.Size([4, 13]) 
Epoch: 1/2,steps 11/45, inputs: torch.Size([4, 13]) 
Epoch: 1/2,steps 16/45, inputs: torch.Size([4, 13]) 
Epoch: 1/2,steps 21/45, inputs: torch.Size([4, 13]) 
Epoch: 1/2,steps 26/45, inputs: torch.Size([4, 13]) 
Epoch: 1/2,steps 31/45, inputs: torch.Size([4, 13]) 
Epoch: 1/2,steps 36/45, inputs: torch.Size([4, 13]) 
Epoch: 1/2,steps 41/45, inputs: torch.Size([4, 13]) 
Epoch: 2/2,steps 1/45, inputs: torch.Size([4, 13]) 
Epoch: 2/2,steps 6/45, inputs: torch.Size([4, 13]) 
Epoch: 2/2,steps 11/45, inputs: torch.Size([4, 13]) 
Epoch: 2/2,steps 16/45, inputs: torch.Size([4, 13]) 
Epoch: 2/2,steps 21/45, inputs: torch.Size([4, 13]) 
Epoch: 2/2,steps 26/45, inputs: torch.Size([4, 13]) 
Epoch: 2/2,steps 31/45, inputs: torch.Size([4, 13]) 
Epoch: 2/2,steps 36/45, inputs: torch.Size([4, 13]) 
Epoch: 2/2,steps 41/45, inputs: torch.Size([4, 13]) 


In [ ]:
torchvision.datasets.MNIST()
torchvision.datasets.FashionMNIST()