In [1]:
import torch

In [2]:
x = torch.empty(1)
x


tensor([1.6647e+26])

In [3]:
x = torch.empty(3)
x


tensor([3.1145e+02, 3.0716e-41, 0.0000e+00])

In [4]:
x = torch.empty(3,2)
x


tensor([[0.0000e+00, 7.4269e-44],
        [1.3108e-08, 8.3967e-07],
        [1.0802e-05, 1.3542e-05]])

In [5]:
#random tensor

x = torch.rand(2,2)
x

tensor([[0.2417, 0.4718],
        [0.6770, 0.2465]])

In [6]:
#random tensor

x = torch.zeros(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

In [7]:
#random tensor

x = torch.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

In [8]:
x.dtype

torch.float32

In [9]:
#random tensor

x = torch.ones(2,2,dtype=torch.double)
x

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [10]:
#random tensor

x = torch.ones(2,2,dtype=torch.int)
x

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [11]:
x.size()

torch.Size([2, 2])

In [12]:
#create tensor from limit

x = torch.tensor([2,3])
x

tensor([2, 3])

## Tensor operation

In [13]:
x= torch.rand(2,2)
y=torch.rand(2,2)
z=x+y
x,y,z

(tensor([[0.2073, 0.7680],
         [0.2999, 0.6465]]),
 tensor([[0.4890, 0.6524],
         [0.1788, 0.0287]]),
 tensor([[0.6963, 1.4204],
         [0.4787, 0.6753]]))

In [14]:
torch.add(x,y)

tensor([[0.6963, 1.4204],
        [0.4787, 0.6753]])

In [15]:
y.add(x) 
y

tensor([[0.4890, 0.6524],
        [0.1788, 0.0287]])

 by default if a function has trailing _ then it will perform inplace operation

In [16]:
y.add_(x) 
y

tensor([[0.6963, 1.4204],
        [0.4787, 0.6753]])

In [17]:
z = x-y
z

tensor([[-0.4890, -0.6524],
        [-0.1788, -0.0287]])

In [18]:
z= torch.sub(x,y)

In [19]:
z = torch.mul(x,y)
z

tensor([[0.1443, 1.0908],
        [0.1435, 0.4366]])

In [20]:
x.mul_(y)

tensor([[0.1443, 1.0908],
        [0.1435, 0.4366]])

# Slicing Operation

In [21]:
x = torch.rand(5,3)

In [22]:
x

tensor([[0.7956, 0.3020, 0.6200],
        [0.2170, 0.1211, 0.2167],
        [0.0542, 0.3470, 0.3396],
        [0.2478, 0.2027, 0.9662],
        [0.6605, 0.1692, 0.3646]])

In [23]:
x[1,:]


tensor([0.2170, 0.1211, 0.2167])

In [24]:
x[1,1].item()

0.12113058567047119

## Reshaping Tensor

In [25]:
x

tensor([[0.7956, 0.3020, 0.6200],
        [0.2170, 0.1211, 0.2167],
        [0.0542, 0.3470, 0.3396],
        [0.2478, 0.2027, 0.9662],
        [0.6605, 0.1692, 0.3646]])

In [26]:
x.view(x.size())

tensor([[0.7956, 0.3020, 0.6200],
        [0.2170, 0.1211, 0.2167],
        [0.0542, 0.3470, 0.3396],
        [0.2478, 0.2027, 0.9662],
        [0.6605, 0.1692, 0.3646]])

numpy to tensor and tensor to numpy

In [27]:
import numpy as np

In [28]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [29]:
b=a.numpy()

If your tensor is loaded on cpu modify numpy array will automatically modify tensor because both share memory location

In [30]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [31]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [32]:
a = np.ones(5)

In [33]:
a

array([1., 1., 1., 1., 1.])

In [34]:
b = torch.from_numpy(a)

In [35]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [36]:
a+=1

In [37]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [38]:
b+=1

In [39]:
a

array([3., 3., 3., 3., 3.])

In [40]:
torch.cuda.is_available()

True

In [41]:
device = torch.device("cuda")

In [42]:
device

device(type='cuda')

In [43]:
x = torch.ones(5,device=device)

In [44]:
device

device(type='cuda')

In [45]:
x.to(device)

tensor([1., 1., 1., 1., 1.], device='cuda:0')

In [46]:
x.to("cpu")

tensor([1., 1., 1., 1., 1.])