## PyTorch Tutorial 10 - Dataset Transforms

In [3]:
import torch 
import torchvision 

dataset = torchvision.datasets.MNIST(

    root='./data',transform=torchvision.transforms.ToTensor(),download=True
)

  0%|          | 0/9912422 [00:00<?, ?it/s]

Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw



  0%|          | 0/28881 [00:00<?, ?it/s]

Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw



  0%|          | 0/1648877 [00:00<?, ?it/s]

Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw



  0%|          | 0/4542 [00:00<?, ?it/s]

Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw



In [6]:
from torch.utils.data import Dataset,DataLoader
import numpy as np
class WineDatset(Dataset):

    def __init__(self,transform = None) -> None:
        super().__init__()
        xy  = np.loadtxt("../wine.csv",delimiter=",",dtype = np.float32,skiprows=1)
        self.x = xy[:,1:]
        self.y = xy[:,:1]
        self.n_samples = xy.shape[0]
        self.transform = transform

    
    def __len__(self):
        


        return self.n_samples


    
    def __getitem__(self, index):
        samples=  self.x[index],self.y[index]
        if self.transform is not None:
            samples = self.transform(samples)
        return samples









In [5]:

class ToTensor():

     def __call__(self, sample):
        x,y = sample 
        return torch.from_numpy(x),torch.from_numpy(y)


In [13]:
dataset = WineDatset(transform=ToTensor())
first_dataset = dataset[0]
x,y = first_dataset
x,y

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
         3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
         1.0650e+03]),
 tensor([1.]))

In [14]:
dataset = WineDatset()
first_dataset = dataset[0]
x,y = first_dataset
x,y

(array([1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
        3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
        1.065e+03], dtype=float32),
 array([1.], dtype=float32))

In [15]:
class MutTransform:

    def __init__(self,factor) -> None:
        self.factor = factor

    def __call__(self,sample):
        x,y = sample
        x*=self.factor
        return x,y
    
    

In [19]:
composed = torchvision.transforms.Compose([ToTensor(),MutTransform(4)])

In [20]:
dataset = WineDatset(transform=composed)
first_dataset = dataset[0]
x,y = first_dataset
x,y

(tensor([5.6920e+01, 6.8400e+00, 9.7200e+00, 6.2400e+01, 5.0800e+02, 1.1200e+01,
         1.2240e+01, 1.1200e+00, 9.1600e+00, 2.2560e+01, 4.1600e+00, 1.5680e+01,
         4.2600e+03]),
 tensor([1.]))