## PyTorch Tutorial 03 - Gradient Calculation With Autograd

In [1]:
import torch

In [2]:
x= torch.randn(3,requires_grad=True)

In [3]:
x

tensor([-0.1678, -1.4346, -1.1368], requires_grad=True)

In [5]:
## It creates computational graph if required_grad is True

![image](https://user-images.githubusercontent.com/115451707/201963865-b9f4ca24-46b9-493b-9def-401da9b0aaa2.png)


In [4]:
y=x+2

In [6]:
y

tensor([1.8322, 0.5654, 0.8632], grad_fn=<AddBackward0>)

In [8]:
z = y*y*2
z = z.mean()
z

tensor(2.9477, grad_fn=<MeanBackward0>)

In [9]:
z.backward()

In [11]:
x

tensor([-0.1678, -1.4346, -1.1368], requires_grad=True)

In [10]:
x.grad

tensor([2.4429, 0.7538, 1.1509])

In [13]:
x = torch.randn(3,requires_grad=True)
y=x+2
z = y*y*2
z

tensor([14.0869,  8.4866,  8.0468], grad_fn=<MulBackward0>)

In [16]:
v = torch.tensor([0.1,0.1,0.001],dtype=torch.float32)
z.backward(v)

In [17]:
#preventing grad history

In [19]:
x = torch.randn(3,requires_grad=True)
x

tensor([ 0.0024, -0.7014,  0.3457], requires_grad=True)

In [20]:
x.requires_grad_(False)

tensor([ 0.0024, -0.7014,  0.3457])

In [22]:
x = torch.randn(3,requires_grad=True)
x.detach()

tensor([ 0.1543, -0.2562,  1.2693])

In [24]:
x = torch.randn(3,requires_grad=True)
with torch.no_grad():
    y =x+2
y

tensor([1.5345, 3.2806, 2.5114])

In [25]:
x = torch.randn(3,requires_grad=True)

y =x+2
y

tensor([2.4341, 2.3706, 1.5862], grad_fn=<AddBackward0>)

In [43]:
#dummy training examples

weights = torch.ones(4,requires_grad=True)

In [37]:
weights

tensor([1., 1., 1., 1.], requires_grad=True)

In [38]:
for epoch in range(3):
    model_ouput = (weights*3).sum()
    model_ouput.backward()
    print(weights.grad)
    weights.grad.zero_()


tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [40]:
weights

tensor([1., 1., 1., 1.], requires_grad=True)

In [45]:
optimizer = torch.optim.SGD([weights],lr=0.01)

In [46]:
optimizer.step()

In [47]:
optimizer

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [48]:
optimizer.zero_grad()