In [1]:
import torch

In [2]:
x = torch.arange(4.0)

In [3]:
x

tensor([0., 1., 2., 3.])

In [4]:
torch.arange(4.0, requires_grad=True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [7]:
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [9]:
print(x.grad)

None


In [10]:
y = 2*torch.dot(x,x)

In [11]:
y

tensor(28., grad_fn=<MulBackward0>)

In [13]:
y.backward()

In [14]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [15]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [16]:
y

tensor(28., grad_fn=<MulBackward0>)

In [17]:
x.grad == 4*x

tensor([True, True, True, True])

In [18]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [19]:
y=x.sum()

In [20]:
y.backward()

In [21]:
x.grad

tensor([1., 1., 1., 1.])

In [22]:
y

tensor(6., grad_fn=<SumBackward0>)

In [24]:
x.sum()

tensor(6., grad_fn=<SumBackward0>)

In [25]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [26]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [27]:
y=x

In [29]:
y=x.sum()

In [31]:
y.backward()

In [32]:
x.grad

tensor([1., 1., 1., 1.])

In [33]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [34]:
y = x*x

In [35]:
y.sum().backward()

In [36]:
x.grad

tensor([0., 2., 4., 6.])

In [37]:
x

tensor([0., 1., 2., 3.], requires_grad=True)